<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseScore extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('score');
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('competition_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('question', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('time', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('tries', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('lang', 'string', 20, array('type' => 'string', 'length' => '20'));
  }

  public function setUp()
  {
    $this->hasOne('Competition', array('local' => 'competition_id',
                                       'foreign' => 'id'));

    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));
  }
}