<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCompetition extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('competition');
    $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('name', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('questions', 'integer', null, array('type' => 'integer'));
  }

  public function setUp()
  {
    $this->hasMany('Score', array('local' => 'id',
                                  'foreign' => 'competition_id'));

    $this->hasMany('Rank', array('local' => 'id',
                                 'foreign' => 'competition_id'));
  }
}