<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRank extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('rank');
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('competition_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('rank', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('points', 'integer', null, array('type' => 'integer'));
  }

  public function setUp()
  {
    $this->hasOne('Competition', array('local' => 'competition_id',
                                       'foreign' => 'id'));

    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));
  }
}