<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUser extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('user');
    $this->hasColumn('id', 'integer', null, array('type' => 'integer', 'primary' => true, 'autoincrement' => true));
    $this->hasColumn('handle', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('country', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('fb', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('tc', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('tc_handle', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('tc_rating', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('votes', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('voted', 'string', 200, array('type' => 'string', 'length' => '200'));
  }

  public function setUp()
  {
    $this->hasMany('Score', array('local' => 'id',
                                  'foreign' => 'user_id'));

    $this->hasMany('Rank', array('local' => 'id',
                                 'foreign' => 'user_id'));
  }
}