<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Competition extends BaseCompetition
{

  public function getRanksQuery($form) {
    $query = Doctrine_Query::create()
              ->from('Rank r, r.User u')
              ->andWhere('r.competition_id = ?',$this->getId());
    if ($form->getValue('country')!="") {
      $query->andWhere('u.country = ?',$form->getValue('country'));
    }
    if ($form->getValue('handle')!="") {
      $query->andWhere('u.handle = ?',$form->getValue('handle'));
    }
    if ($form->getValue('fb_users')!=null) {
      $query->andWhere('u.fb != 0');
    }
    for($i=0;$i<$form->getOption('questions');$i++) {
      if ($form->getValue('question_'.$i)!=null) {
        $s = "s".$i;
        $query->andWhere("u.id IN (SELECT $s.user_id FROM Score $s WHERE competition_id=".$this->getId()." AND $s.question=$i AND $s.time!=-1)");
      }
    }
    return $query;
  }

}
