<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rank extends BaseRank
{
  public function getScores() {
    return Doctrine::getTable('Score')->createQuery()
        ->where('user_id = ?',$this->getUserId())
        ->andWhere('competition_id = ?',$this->getCompetitionId())
        ->orderBy('question ASC')
        ->execute();
  }
}
