<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Score extends BaseScore
{

  public function getLangIcon($text) {
    $class = "icon icon_".$this->getLang();
    return '<span title="'.$this->getLang().'" class="'.$class.'">'.$text.'</span>';
  }

  public function getFormatedTime() {
    $score = $this->getTime();
    if ($score==-1)
      return "--";
    $s = sprintf("%02d",$score/(60*60)).":".sprintf("%02d",($score/60)%60).":".sprintf("%02d",$score%60);
    return $this->getLangIcon($s);
  }

}
