<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{

  public function getFBUser($user_id) 
  {
    return $this->createQuery()->where('fb = ?',$user_id)->fetchOne();
  }
  
  public function getCountries()
  {
    $arr = $this->createQuery()->select('country,count(*) as c')->groupBy('country')->fetchArray();
    $countries = array('' => 'Any');
    foreach($arr as $user) {
      $countries[$user['country']] = $user['country'].' ('.$user['c'].')';
    }
    return $countries;
  }

}
