<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{

  public function getHandleFormatted() 
  {
    if ($this->getTc()==null) {
      return $this->getHandle();
    }
    $h = "";
    $url = "http://www.topcoder.com/tc?module=MemberProfile&cr=".$this->getTc();
    $r = $this->getTcRating();
    if ($r<900) {
      $c = "Gray";
    } else if ($r<1200) {
      $c = "Green";
    } else if ($r<1500) {
      $c = "Blue";
    } else if ($r<2200) {
      $c = "Yellow";
    } else {
      $c = "Red";
    }
    $h = "<a href=\"$url\" class=\"coderText$c\">".$this->getTcHandle()."</a>";
    if ($this->getTcHandle()!=$this->getHandle()) {
      $h = $this->getHandle()."<br/>$h";
    }
    return $h;
  }

  public function getFormattedVotes() 
  {
    return '<br /><em>'.$this->getVotes().'</em>';
  }
}
